// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	AppControllerGetDataData,
	AppControllerGetDataResponses,
	ImageClientControllerTestConnectionData,
	ImageClientControllerTestConnectionResponses,
	ServerDeitiesControllerGetDeitiesByCategoryData,
	ServerDeitiesControllerGetDeitiesByCategoryResponses,
	ServerDeitiesControllerGetDeitiesByLocationData,
	ServerDeitiesControllerGetDeitiesByLocationResponses,
	ServerDeitiesControllerGetDeityByIdData,
	ServerDeitiesControllerGetDeityByIdResponses,
	ServerLocationControllerCreateData,
	ServerLocationControllerCreateResponses,
	ServerLocationControllerGetAllByParentIdData,
	ServerLocationControllerGetAllByParentIdResponses,
	ServerLocationControllerGetAllByTypeData,
	ServerLocationControllerGetAllByTypeResponses,
	ServerLocationControllerGetByIdData,
	ServerLocationControllerGetByIdResponses,
	ServerLocationControllerUpdateData,
	ServerLocationControllerUpdateResponses,
	ServerRaceControllerGetAllRacesData,
	ServerRaceControllerGetAllRacesResponses,
	ServerRaceControllerGetRaceWithAbilitiesData,
	ServerRaceControllerGetRaceWithAbilitiesResponses,
	ServerSecurityControllerGetMeData,
	ServerSecurityControllerGetMeResponses,
	ServerSecurityControllerLoginData,
	ServerSecurityControllerLoginResponses,
	ServerSecurityControllerLogoutData,
	ServerSecurityControllerLogoutResponses,
	ServerSecurityControllerRefreshSessionData,
	ServerSecurityControllerRefreshSessionResponses,
	ServerSecurityControllerResetUserPasswordFromTokenData,
	ServerSecurityControllerResetUserPasswordFromTokenResponses,
	ServerSecurityControllerSignupData,
	ServerSecurityControllerSignupResponses,
	ServerSecurityControllerStartUserPasswordResetData,
	ServerSecurityControllerStartUserPasswordResetResponses,
	ServerSecurityControllerVerifyEmailByTokenData,
	ServerSecurityControllerVerifyEmailByTokenResponses,
} from "./types.gen";

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export const appControllerGetData = <ThrowOnError extends boolean = false>(
	options?: Options<AppControllerGetDataData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		AppControllerGetDataResponses,
		unknown,
		ThrowOnError
	>({ url: "/api", ...options });

export const serverDeitiesControllerGetDeitiesByCategory = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		ServerDeitiesControllerGetDeitiesByCategoryData,
		ThrowOnError
	>,
) =>
	(options.client ?? client).get<
		ServerDeitiesControllerGetDeitiesByCategoryResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/deities/category/{category}", ...options });

export const serverDeitiesControllerGetDeityById = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerDeitiesControllerGetDeityByIdData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ServerDeitiesControllerGetDeityByIdResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/deities/id/{id}", ...options });

export const serverDeitiesControllerGetDeitiesByLocation = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		ServerDeitiesControllerGetDeitiesByLocationData,
		ThrowOnError
	>,
) =>
	(options.client ?? client).get<
		ServerDeitiesControllerGetDeitiesByLocationResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/deities/location/{location}", ...options });

export const imageClientControllerTestConnection = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ImageClientControllerTestConnectionData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ImageClientControllerTestConnectionResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/image-client/test/{id}", ...options });

export const serverLocationControllerGetAllByType = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerLocationControllerGetAllByTypeData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ServerLocationControllerGetAllByTypeResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/location", ...options });

export const serverLocationControllerGetAllByParentId = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerLocationControllerGetAllByParentIdData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ServerLocationControllerGetAllByParentIdResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/location/by-parent/{id}", ...options });

export const serverLocationControllerGetById = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerLocationControllerGetByIdData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ServerLocationControllerGetByIdResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/location/id/{id}", ...options });

export const serverLocationControllerCreate = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerLocationControllerCreateData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		ServerLocationControllerCreateResponses,
		unknown,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/api/location/new",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverLocationControllerUpdate = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerLocationControllerUpdateData, ThrowOnError>,
) =>
	(options.client ?? client).patch<
		ServerLocationControllerUpdateResponses,
		unknown,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/api/location/update/{id}",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverRaceControllerGetAllRaces = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<ServerRaceControllerGetAllRacesData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ServerRaceControllerGetAllRacesResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/race", ...options });

export const serverRaceControllerGetRaceWithAbilities = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerRaceControllerGetRaceWithAbilitiesData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		ServerRaceControllerGetRaceWithAbilitiesResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/race/{id}", ...options });

export const serverSecurityControllerSignup = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerSecurityControllerSignupData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		ServerSecurityControllerSignupResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/auth/signup",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverSecurityControllerLogin = <
	ThrowOnError extends boolean = false,
>(
	options: Options<ServerSecurityControllerLoginData, ThrowOnError>,
) =>
	(options.client ?? client).post<
		ServerSecurityControllerLoginResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/auth/login",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverSecurityControllerLogout = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<ServerSecurityControllerLogoutData, ThrowOnError>,
) =>
	(options?.client ?? client).post<
		ServerSecurityControllerLogoutResponses,
		unknown,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/api/auth/logout",
		...options,
	});

export const serverSecurityControllerVerifyEmailByToken = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		ServerSecurityControllerVerifyEmailByTokenData,
		ThrowOnError
	>,
) =>
	(options.client ?? client).get<
		ServerSecurityControllerVerifyEmailByTokenResponses,
		unknown,
		ThrowOnError
	>({ url: "/api/auth/verify-email", ...options });

export const serverSecurityControllerStartUserPasswordReset = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		ServerSecurityControllerStartUserPasswordResetData,
		ThrowOnError
	>,
) =>
	(options.client ?? client).post<
		ServerSecurityControllerStartUserPasswordResetResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/auth/password-reset-request",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverSecurityControllerResetUserPasswordFromToken = <
	ThrowOnError extends boolean = false,
>(
	options: Options<
		ServerSecurityControllerResetUserPasswordFromTokenData,
		ThrowOnError
	>,
) =>
	(options.client ?? client).post<
		ServerSecurityControllerResetUserPasswordFromTokenResponses,
		unknown,
		ThrowOnError
	>({
		url: "/api/auth/password-reset",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});

export const serverSecurityControllerGetMe = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<ServerSecurityControllerGetMeData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ServerSecurityControllerGetMeResponses,
		unknown,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/api/auth/me",
		...options,
	});

export const serverSecurityControllerRefreshSession = <
	ThrowOnError extends boolean = false,
>(
	options?: Options<ServerSecurityControllerRefreshSessionData, ThrowOnError>,
) =>
	(options?.client ?? client).get<
		ServerSecurityControllerRefreshSessionResponses,
		unknown,
		ThrowOnError
	>({
		security: [{ scheme: "bearer", type: "http" }],
		url: "/api/auth/refresh",
		...options,
	});
