// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type OverviewObjectDto = {
    id: string;
    name: string;
};

export type GetDeityByIdResponseDto = {
    id: string;
    name: string;
    description: string;
    domain: Array<{
        id?: string;
        name?: string;
        type?: 'cleric' | 'druid' | 'warlock';
    }>;
    imageUrl?: string;
};

export type GetLocationByIdResponseDto = {
    name: string;
    id: string;
    description?: string;
    type: 'plane' | 'region' | 'city' | 'shop' | 'mine' | 'forest' | 'beach' | 'wilderness';
    parentId?: string;
    imageUrl?: string;
};

export type LocationCreationDto = {
    name: string;
    description?: string;
    type: 'plane' | 'region' | 'city' | 'shop' | 'mine' | 'forest' | 'beach' | 'wilderness';
    parentId?: string;
};

export type LocationCreateResponseDto = {
    id: string;
    name: string;
    description?: string;
    parentId?: string;
    imageId?: string;
};

export type LocationUpdateDto = {
    name?: string;
    description?: string;
    type?: 'plane' | 'region' | 'city' | 'shop' | 'mine' | 'forest' | 'beach' | 'wilderness';
    parentId?: string;
};

export type LocationUpdateResponseDto = {
    success: boolean;
};

export type GetRaceByIdResponseDto = {
    id: string;
    name: string;
    description: string;
    ageDescription: string;
    sizeDescription: string;
    type: 'fey' | 'humanoid';
    speed: number;
    knownLanguages: string;
    racialAbilities: Array<{
        name?: string;
        description?: string;
    }>;
};

export type SignupBodyDto = {
    email: string;
    password: string;
    name: string;
};

export type SignUpLocalResponseDto = {
    id: string;
    displayName: string;
    success: boolean;
    roles: Array<'player' | 'dev' | 'dm' | 'admin'>;
    sessionId: string;
};

export type LoginBodyDto = {
    email: string;
    password: string;
};

export type LoginResponseDto = {
    id: string;
    displayName: string;
    success: boolean;
    roles: Array<'player' | 'dev' | 'dm' | 'admin'>;
    sessionId: string;
};

export type LogoutResponseDto = {
    success: boolean;
};

export type GetVerifyEmailResponseDto = {
    success: boolean;
};

export type PasswordResetRequestDto = {
    email: string;
};

export type PasswordResetRequestResponseDto = {
    success: boolean;
};

export type PasswordResetDto = {
    resetToken: string;
    password: string;
};

export type PasswordResetResponseDto = {
    success: boolean;
};

export type GetMeResponseDto = {
    id: string;
    email: string;
    roles: Array<'player' | 'dev' | 'dm' | 'admin'>;
    displayName: string;
};

export type GetRefreshResponseDto = {
    sessionId: string;
};

export type AppControllerGetDataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api';
};

export type AppControllerGetDataResponses = {
    200: unknown;
};

export type ServerDeitiesControllerGetDeitiesByCategoryData = {
    body?: never;
    path: {
        category: string;
    };
    query?: never;
    url: '/api/deities/category/{category}';
};

export type ServerDeitiesControllerGetDeitiesByCategoryResponses = {
    200: Array<OverviewObjectDto>;
};

export type ServerDeitiesControllerGetDeitiesByCategoryResponse = ServerDeitiesControllerGetDeitiesByCategoryResponses[keyof ServerDeitiesControllerGetDeitiesByCategoryResponses];

export type ServerDeitiesControllerGetDeityByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/deities/id/{id}';
};

export type ServerDeitiesControllerGetDeityByIdResponses = {
    200: GetDeityByIdResponseDto;
};

export type ServerDeitiesControllerGetDeityByIdResponse = ServerDeitiesControllerGetDeityByIdResponses[keyof ServerDeitiesControllerGetDeityByIdResponses];

export type ServerDeitiesControllerGetDeitiesByLocationData = {
    body?: never;
    path: {
        location: string;
    };
    query?: never;
    url: '/api/deities/location/{location}';
};

export type ServerDeitiesControllerGetDeitiesByLocationResponses = {
    200: Array<OverviewObjectDto>;
};

export type ServerDeitiesControllerGetDeitiesByLocationResponse = ServerDeitiesControllerGetDeitiesByLocationResponses[keyof ServerDeitiesControllerGetDeitiesByLocationResponses];

export type ImageClientControllerTestConnectionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/image-client/test/{id}';
};

export type ImageClientControllerTestConnectionResponses = {
    200: unknown;
};

export type ServerLocationControllerGetAllByTypeData = {
    body?: never;
    path?: never;
    query: {
        type: 'plane' | 'region' | 'city' | 'shop' | 'mine' | 'forest' | 'beach' | 'wilderness';
    };
    url: '/api/location';
};

export type ServerLocationControllerGetAllByTypeResponses = {
    200: Array<OverviewObjectDto>;
};

export type ServerLocationControllerGetAllByTypeResponse = ServerLocationControllerGetAllByTypeResponses[keyof ServerLocationControllerGetAllByTypeResponses];

export type ServerLocationControllerGetAllByParentIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/by-parent/{id}';
};

export type ServerLocationControllerGetAllByParentIdResponses = {
    200: Array<OverviewObjectDto>;
};

export type ServerLocationControllerGetAllByParentIdResponse = ServerLocationControllerGetAllByParentIdResponses[keyof ServerLocationControllerGetAllByParentIdResponses];

export type ServerLocationControllerGetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/id/{id}';
};

export type ServerLocationControllerGetByIdResponses = {
    200: GetLocationByIdResponseDto;
};

export type ServerLocationControllerGetByIdResponse = ServerLocationControllerGetByIdResponses[keyof ServerLocationControllerGetByIdResponses];

export type ServerLocationControllerCreateData = {
    body: LocationCreationDto & {
        image?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/api/location/new';
};

export type ServerLocationControllerCreateResponses = {
    201: LocationCreateResponseDto;
};

export type ServerLocationControllerCreateResponse = ServerLocationControllerCreateResponses[keyof ServerLocationControllerCreateResponses];

export type ServerLocationControllerUpdateData = {
    body: LocationUpdateDto & {
        image?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/location/update/{id}';
};

export type ServerLocationControllerUpdateResponses = {
    200: LocationUpdateResponseDto;
};

export type ServerLocationControllerUpdateResponse = ServerLocationControllerUpdateResponses[keyof ServerLocationControllerUpdateResponses];

export type ServerRaceControllerGetAllRacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/race';
};

export type ServerRaceControllerGetAllRacesResponses = {
    200: Array<OverviewObjectDto>;
};

export type ServerRaceControllerGetAllRacesResponse = ServerRaceControllerGetAllRacesResponses[keyof ServerRaceControllerGetAllRacesResponses];

export type ServerRaceControllerGetRaceWithAbilitiesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/race/{id}';
};

export type ServerRaceControllerGetRaceWithAbilitiesResponses = {
    200: GetRaceByIdResponseDto;
};

export type ServerRaceControllerGetRaceWithAbilitiesResponse = ServerRaceControllerGetRaceWithAbilitiesResponses[keyof ServerRaceControllerGetRaceWithAbilitiesResponses];

export type ServerSecurityControllerSignupData = {
    body: SignupBodyDto;
    path?: never;
    query?: never;
    url: '/api/auth/signup';
};

export type ServerSecurityControllerSignupResponses = {
    201: SignUpLocalResponseDto;
};

export type ServerSecurityControllerSignupResponse = ServerSecurityControllerSignupResponses[keyof ServerSecurityControllerSignupResponses];

export type ServerSecurityControllerLoginData = {
    body: LoginBodyDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type ServerSecurityControllerLoginResponses = {
    200: LoginResponseDto;
};

export type ServerSecurityControllerLoginResponse = ServerSecurityControllerLoginResponses[keyof ServerSecurityControllerLoginResponses];

export type ServerSecurityControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type ServerSecurityControllerLogoutResponses = {
    201: LogoutResponseDto;
};

export type ServerSecurityControllerLogoutResponse = ServerSecurityControllerLogoutResponses[keyof ServerSecurityControllerLogoutResponses];

export type ServerSecurityControllerVerifyEmailByTokenData = {
    body?: never;
    path?: never;
    query: {
        verificationToken: string;
    };
    url: '/api/auth/verify-email';
};

export type ServerSecurityControllerVerifyEmailByTokenResponses = {
    200: GetVerifyEmailResponseDto;
};

export type ServerSecurityControllerVerifyEmailByTokenResponse = ServerSecurityControllerVerifyEmailByTokenResponses[keyof ServerSecurityControllerVerifyEmailByTokenResponses];

export type ServerSecurityControllerStartUserPasswordResetData = {
    body: PasswordResetRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset-request';
};

export type ServerSecurityControllerStartUserPasswordResetResponses = {
    201: PasswordResetRequestResponseDto;
};

export type ServerSecurityControllerStartUserPasswordResetResponse = ServerSecurityControllerStartUserPasswordResetResponses[keyof ServerSecurityControllerStartUserPasswordResetResponses];

export type ServerSecurityControllerResetUserPasswordFromTokenData = {
    body: PasswordResetDto;
    path?: never;
    query?: never;
    url: '/api/auth/password-reset';
};

export type ServerSecurityControllerResetUserPasswordFromTokenResponses = {
    201: PasswordResetResponseDto;
};

export type ServerSecurityControllerResetUserPasswordFromTokenResponse = ServerSecurityControllerResetUserPasswordFromTokenResponses[keyof ServerSecurityControllerResetUserPasswordFromTokenResponses];

export type ServerSecurityControllerGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type ServerSecurityControllerGetMeResponses = {
    200: GetMeResponseDto;
};

export type ServerSecurityControllerGetMeResponse = ServerSecurityControllerGetMeResponses[keyof ServerSecurityControllerGetMeResponses];

export type ServerSecurityControllerRefreshSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type ServerSecurityControllerRefreshSessionResponses = {
    200: GetRefreshResponseDto;
};

export type ServerSecurityControllerRefreshSessionResponse = ServerSecurityControllerRefreshSessionResponses[keyof ServerSecurityControllerRefreshSessionResponses];
