version: '3'
name: unteris-e2e
services:
  postgres:
    image: postgres
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
  redis:
    image: redis
    ports:
      - '26379:6379'
