name: unteris

services:
  site:
    image: jmcdo29/unteris-site
    ports:
      - '127.0.0.1:8080:80'
    volumes:
      - './images:/src/dist/apps/site/images'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  server:
    image: jmcdo29/unteris-server
    logging:
      driver: local
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    volumes:
      - './images:/src/images'
    ports:
      - '127.0.0.1:3333:3333'
    depends_on:
      - postgres
      - redis
      - rabbit
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  image-server:
    image: jmcdo29/unteris-image-server
    logging:
      driver: local
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    volumes:
      - './images:/src/images'
    depends_on:
      - postgres
      - rabbit
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  migrations:
    image: jmcdo29/unteris-migrations
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    logging:
      driver: local
    depends_on:
      - postgres
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: '--include-stopped --revive-stopped --schedule "0 0 * * * *" --label-enable'
  postgres:
    image: jmcdo29/unteris-postgres
    env_file: .env
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.1
    ports:
      - '127.0.0.1:6380:6379'
    volumes:
      - './redis.conf:/usr/local/etc/redis/redis.conf'
    command: redis-server /usr/local/etc/redis/redis.conf
  rabbitmq:
    image: rabbitmq:3.12.6
    ports:
      - '127.0.0.1:5673:5672'
    volumes:
      - './rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
