version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: apps/postgres/Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unteris
  redis:
    image: redis
    ports:
      - '6379:6379'
