onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - argon2
  - cypress
  - esbuild
  - less
  - nx
#  - sharp
  - unrs-resolver
  - useragent-ng
ignoredBuiltDependencies:
  - sharp
supportedArchitectures:
  os:
  - linux
  cpu:
  - x64
