erDiagram
    DeityCategory ||--|{ Deity : "contains"
    Deity ||--|{ Deity_Domain : "belongs to"
    Domain ||--|{ Deity_Domain : "belongs to"
    Deity ||--|| Location : "resides in"
    Race ||--|{ Racial_Ability : "belongs to"
    User_Account ||--|{ Login_Method : "can have"
    User_Account || --|{ User_Permission : "should have"
    DeityCategory {
        string name
        string id
    }
    Deity {
        string name
        string id
        string description
        string image_url
        string category
        string location
    }
    Domain {
        string name
        string id
        string description
        string type
    }
    Deity_Domain {
        string deity_id
        string domain_id
    }
    Location {
        string id
        string name
        string description
    }
    Race {
        string id
        string name
        string description
        string age_description
        string size_description
        string type
        integer speed
        string known_languages
    }
    Racial_Ability {
        string id
        string race_id
        string name
        string description
    }
    User_Account {
        string id
        string name
        string email
        boolean isVerified
        string photo_url
    }
    User_Permission {
        string id
        string user_id
        string role
    }
    Login_Method {
        string id
        string user_id
        string name
    }
