#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

node_modules/.bin/nx affected:lint --base=HEAD^ --parallel
updatedByLinter=$(git status --porcelain | grep MM | awk '{print $2}')
if [ -z updatedByLinter ]; then
  git add $updatedByLinter
fi
# no longer necessary as the biome lint formats as well
# node_modules/.bin/nx format:write
if git diff --cached --name-only | grep -Eq \(diagram\.mmd\|migrations\/README\); then
  node_modules/.bin/embedme --stdout --strip-embed-comment libs/db/migrations/README.template.md > libs/db/migrations/README.md
  git add libs/db/migrations/README.md
fi
if git diff --cached --name-only | grep -E migrations\/.*\.ts | grep -v 'utils' | grep -Eqv [0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}
then
  echo "Migrations should start with a ULID"
  exit 1
fi
