name: Release

on:
  push:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm i -g pnpm@^8

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile=false

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v2

      - name: Build Projects
        shell: bash
        run: |
          pnpm nx run-many --target=packge --builder=${{ steps.builder.outputs.name }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker List Images
        shell: bash
        run: docker image ls

      - name: Login to Docker Hub
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish
        if: steps.changesets.outputs.hasChangesets == 'false'
        # You can do something when a publish should happen.
        run: pnpm nx run-many --target=publish --parellel
        env:
          DOCKER_TOKEN: ${{ secrets.NPM_TOKEN }}
