name: Release

on:
  push:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}
  CYPRESS_INSTALL_BINARY: 0

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Node/Pnpm Install
        uses: ./.github/actions/install-node-pnpm

      - name: Docker BuildX Install and Cache
        id: builder
        uses: ./.github/actions/docker-with-cache
        with:
          DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Projects
        shell: bash
        run: |
          pnpm nx affected --target=package --configuration=ci --builder=${{ steps.builder.outputs.builder}}

      - name: Docker List Images
        shell: bash
        run: docker image ls
